version: '3.4'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver

  libraryproject.api:
    image: ${DOCKER_REGISTRY-}libraryprojectapi
    build:
      context: .
      dockerfile: LibraryProject.API/Dockerfile
